### ISSUE TITLE
[Client-Bug]启动器的功能欠缺

### ISSUE THREAD

**Issue by mylx2022** [Mylx-Server/BugReport#4]
## 我已经确认： 
- [x] 我已经确定我正在使用官方启动器
- [x] 我已经确定客户端中没有我想要的功能/mod
- [x] 我正在使用 Minecraft Java Edition 
- [x] 我已经在 [Issue Tracker](……/) **中找过我要提出的问题**
- [x] 我已经仔细看过 [常见问题解答](https://github.com/Mylx-Server/BugReport/issues/3) 并无法自行解决问题
- [x] 这是 官方客户端 的问题，并非我所使用的任何修改版本（包括增删mod，修改配置文件）的特定问题

------------------------------------------------------------------

### 环境 Environment

* 操作系统 windows 11
……

### 说明 Description

启动器中多人游戏中不能添加服务器,,希望以后的更新可以添加服务器.

**我预期会发生……？**

### 可能的解决方案 Possible Solution
加上添加服务器的按钮和功能.

**Comment by 0xc0000142** [comment]
fix on build 7
